### ISSUE TITLE
Key creation is not allowed on this service account

### ISSUE THREAD

**Issue by craigivy** [yeltnerb/baremetal1#2]
When running quickstart.sh I receive:

ERROR: (gcloud.iam.service-accounts.keys.create) FAILED_PRECONDITION: Key creation is not allowed on this service account.
- '@type': type.googleapis.com/google.rpc.PreconditionFailure
  violations:
  - description: Key creation is not allowed on this service account.
    subject: projects/anbaremetal/serviceAccounts/anbaremetal-tf-service@anbaremetal.iam.gserviceaccount.com?configvalue=anbaremetal-tf-service%40anbaremetal.iam.gserviceaccount.com
    type: constraints/iam.disableServiceAccountKeyCreation

After running the command a second time the key does get created.  Note, nothing was cleaned up between runs.

Reproduce -
Create new project
run fix-argolis.sh
run quickstart.sh
error is displayed

**Comment by yeltnerb** [comment]
Changed order of download.   please test.

**Comment by yeltnerb** [comment]
Tested and fixed!
